# Generated by Django 5.1.1 on 2024-12-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_grupo_remove_personagem_grupo_remove_poder_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='criador',
            field=models.CharField(default='Criador desconhecido', max_length=100),
        ),
    ]
