# Generated by Django 5.1.1 on 2024-12-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_poder_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
