# Generated by Django 5.1.1 on 2024-12-04 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_personagem_favorito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagem',
            options={'verbose_name_plural': 'Personagens'},
        ),
    ]
