# Generated by Django 5.1.1 on 2024-12-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_personagem_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personagem',
            old_name='raça',
            new_name='raca',
        ),
    ]
