# Generated by Django 5.1.1 on 2024-12-02 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0003_grupo_remove_personagem_grupo_remove_poder_codigo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=5000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='historia/fotos')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='persona.personagem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
