# Generated by Django 5.1.1 on 2024-12-02 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia', '0001_initial'),
        ('persona', '0004_personagem_criador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='personagem',
        ),
        migrations.RemoveField(
            model_name='historia',
            name='preco',
        ),
        migrations.AddField(
            model_name='historia',
            name='autores',
            field=models.TextField(default='Desconhecido'),
        ),
        migrations.AddField(
            model_name='historia',
            name='data_de_lancamento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='historia',
            name='ilustradores',
            field=models.TextField(default='Desconhecido'),
        ),
        migrations.AddField(
            model_name='historia',
            name='nome',
            field=models.CharField(default='História sem nome', max_length=255),
        ),
        migrations.AddField(
            model_name='historia',
            name='personagens',
            field=models.ManyToManyField(related_name='historias', to='persona.personagem'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='descricao',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='historia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_armazenadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
